package main

import (
	_ "github.com/alecthomas/kong"
	_ "github.com/alexedwards/scs/pgxstore"
	_ "github.com/alexedwards/scs/v2"
	_ "github.com/auth0/go-auth0"
	_ "github.com/aws/aws-sdk-go-v2"
	_ "github.com/aws/aws-sdk-go-v2/config"
	_ "github.com/aws/aws-sdk-go-v2/feature/s3/manager"
	_ "github.com/aws/aws-sdk-go-v2/service/s3"
	_ "github.com/circleci/backplane-go/httpserver"
	_ "github.com/coreos/go-oidc/v3/oidc"
	_ "github.com/gin-gonic/gin"
	_ "github.com/go-chi/chi/v5"
	_ "github.com/go-oauth2/oauth2/v4"
	_ "github.com/go-redis/cache/v9"
	_ "github.com/golang-jwt/jwt/v5"
	_ "github.com/google/go-cmp/cmp/cmpopts"
	_ "github.com/google/uuid"
	_ "github.com/gubernator-io/gubernator/v2"
	_ "github.com/hashicorp/go-multierror"
	_ "github.com/hashicorp/go-retryablehttp"
	_ "github.com/jackc/pgx/v5"
	_ "github.com/lestrrat-go/jwx/v3"
	_ "github.com/maypok86/otter/v2"
	_ "github.com/mr-tron/base58"
	_ "github.com/playwright-community/playwright-go"
	_ "github.com/redis/go-redis/v9"
	_ "github.com/sethvargo/go-envconfig"
	_ "github.com/sirupsen/logrus"
	_ "go.mongodb.org/mongo-driver/v2/mongo"
	_ "go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws"
	_ "go.opentelemetry.io/otel"
	_ "golang.org/x/crypto/bcrypt"
	_ "golang.org/x/oauth2"
	_ "golang.org/x/sync/errgroup"
	_ "google.golang.org/grpc"
	_ "gotest.tools/v3"
	_ "k8s.io/klog/v2"
)

func main() {
}
